packages:
  - apps/*
  - packages/*

catalogs:
  angular:
    '@angular/aria': ~21.2.6
    '@angular/cdk': ~21.2.6
    '@angular/common': ~21.2.8
    '@angular/compiler': ~21.2.8
    '@angular/core': ~21.2.8
    '@angular/forms': ~21.2.8
    '@angular/platform-browser': ~21.2.8
    '@angular/router': ~21.2.8

  angular-build:
    '@angular-devkit/core': ~21.2.7
    '@angular-devkit/schematics': ~21.2.7
    '@angular/build': ~21.2.7
    '@angular/cli': ~21.2.7
    '@angular/compiler-cli': ~21.2.8
    '@angular/language-service': ~21.2.8
    '@schematics/angular': ~21.2.7
    ng-packagr: ~21.2.2

  angular-eslint:
    '@angular-eslint/eslint-plugin': 21.3.1
    '@angular-eslint/eslint-plugin-template': 21.3.1
    '@angular-eslint/template-parser': 21.3.1

  analogjs:
    '@analogjs/vite-plugin-angular': 2.4.7
    '@analogjs/vitest-angular': 2.4.7

  nx:
    '@nx/angular': 22.6.5
    '@nx/devkit': 22.6.5
    '@nx/eslint-plugin': 22.6.5
    '@nx/js': 22.6.5
    '@nx/playwright': 22.6.5
    '@nx/vite': 22.6.5
    '@nx/vitest': 22.6.5
    '@nx/web': 22.6.5
    '@nx/workspace': 22.6.5
    nx: 22.6.5

  vitest:
    '@vitest/browser': ~4.1.4
    '@vitest/browser-playwright': ~4.1.4
    '@vitest/coverage-v8': 4.1.4
    '@vitest/ui': 4.1.4
    vitest: 4.1.4

  playwright:
    '@playwright/test': ^1.59.1
    eslint-plugin-playwright: ^2.10.1

  testing-library:
    '@testing-library/angular': ^19.2.1
    '@testing-library/dom': ^10.4.1
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/user-event': ^14.6.1

  swc:
    '@swc-node/register': 1.11.1
    '@swc/core': 1.15.24
    '@swc/helpers': 0.5.21

  tailwind:
    '@tailwindcss/forms': ^0.5.11
    '@tailwindcss/postcss': ^4.2.2
    autoprefixer: ^10.4.27
    postcss: ^8.5.9
    postcss-url: ~10.1.3
    tailwindcss: ^4.2.2

  shiki:
    '@shikijs/core': ^4.0.2
    '@shikijs/types': ^4.0.2
    shiki: ^4.0.2

autoInstallPeers: true

onlyBuiltDependencies:
  - '@swc/core'
  - msw
  - nx
  - simple-git-hooks

strictPeerDependencies: false
