import { workspaceRoot } from '@nx/devkit';
import { nxE2EPreset } from '@nx/playwright/preset';
import { defineConfig, devices } from '@playwright/test';

// For CI, you may want to set BASE_URL to the deployed application.
const baseURL = process.env['BASE_URL'] ?? 'http://localhost:4200';
const isCI = Boolean(process.env['CI']);

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const preset = nxE2EPreset(__filename, { testDir: './src' });

export default defineConfig({
  ...preset,
  // The dedicated `a11y` target owns the route-sweep accessibility scan
  // (src/accessibility.spec.ts); keep it out of the functional e2e run so the
  // two suites stay independently runnable. The slash anchor is deliberate: it
  // must not also match the existing forms/**/*-accessibility.spec.ts specs.
  testIgnore: /[\\/]accessibility\.spec\.ts$/,
  updateSnapshots: isCI ? 'none' : 'missing',
  forbidOnly: isCI,
  retries: isCI ? 1 : 0,
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
  ],
  expect: {
    toMatchAriaSnapshot: {
      children: 'contain',
      pathTemplate: '{testDir}/__snapshots__/{testFilePath}/{arg}{ext}',
    },
    toHaveScreenshot: {
      animations: 'disabled',
      caret: 'hide',
      scale: 'css',
      // Tolerance for same-OS rendering jitter. Baselines are platform-scoped
      // via the {platform} token below, so CI compares Linux-vs-Linux and local
      // dev compares against its own OS baseline — never across operating
      // systems. Cross-OS comparison is unfixable by tolerance: Chromium's font
      // metrics shift the intrinsic width of fit-content elements by ~7px
      // between macOS and Linux, which is a hard dimension mismatch (different
      // image sizes can't be pixel-diffed at all). 5% only needs to absorb
      // subpixel/antialiasing jitter within a single OS, and still catches real
      // layout regressions.
      maxDiffPixelRatio: 0.05,
      // {platform} keeps macOS (darwin) and Linux baselines in separate dirs.
      // Linux baselines are generated by the "Update Snapshots" workflow
      // (.github/workflows/update-snapshots.yml, runs on ubuntu-latest); local
      // darwin baselines are written on first run via updateSnapshots:'missing'.
      pathTemplate:
        '{testDir}/__screenshots__{/projectName}{/platform}/{testFilePath}/{arg}{ext}',
    },
  },
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    ...preset.use,
    baseURL,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'pnpm nx serve demo',
    url: 'http://localhost:4200',
    reuseExistingServer: !isCI,
    cwd: workspaceRoot,
    timeout: 240000,
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
